import type { PricingManifest } from './types.js';

export const pricingManifest: PricingManifest = {
  retrieved_at: '2026-03-17',
  pricing: {
    auto: {
      display_name: 'Auto',
      provider: 'cursor',
      input_per_million: 1.25,
      cache_write_per_million: 1.25,
      cache_read_per_million: 0.25,
      output_per_million: 6.0,
      apply_max_mode_uplift: false,
      source_url: 'https://cursor.com/docs/models-and-pricing',
      notes: 'Cursor Auto + Composer pool fixed token pricing.',
    },
    'composer-1': {
      display_name: 'Composer 1',
      provider: 'cursor',
      input_per_million: 1.25,
      cache_write_per_million: 1.25,
      cache_read_per_million: 0.125,
      output_per_million: 10.0,
      apply_max_mode_uplift: false,
      source_url: 'https://cursor.com/docs/models-and-pricing',
      notes: 'Cursor model pricing from Cursor Docs API pool table.',
    },
    'composer-1.5': {
      display_name: 'Composer 1.5',
      provider: 'cursor',
      input_per_million: 3.5,
      cache_write_per_million: 3.5,
      cache_read_per_million: 0.35,
      output_per_million: 17.5,
      apply_max_mode_uplift: false,
      source_url: 'https://cursor.com/docs/models-and-pricing',
      notes: 'Cursor model pricing from Cursor Docs API pool table.',
    },
    'composer-2': {
      display_name: 'Composer 2',
      provider: 'cursor',
      input_per_million: 0.5,
      cache_write_per_million: 0.5,
      cache_read_per_million: 0.2,
      output_per_million: 2.5,
      apply_max_mode_uplift: false,
      source_url: 'https://cursor.com/docs/models-and-pricing',
      notes: 'Cursor Composer 2 pricing from the Auto + Composer pool table.',
    },
    'composer-2-fast': {
      display_name: 'Composer 2 Fast',
      provider: 'cursor',
      input_per_million: 1.5,
      cache_write_per_million: 1.5,
      cache_read_per_million: 0.6,
      output_per_million: 7.5,
      apply_max_mode_uplift: false,
      source_url: 'https://cursor.com/docs/models/cursor-composer-2',
      notes:
        'Cursor docs explicitly publish fast input/output pricing; cache-read and cache-write values are inferred as a 3x multiple of Composer 2 standard pricing.',
    },
    'claude-4.5-haiku': {
      display_name: 'Claude 4.5 Haiku',
      provider: 'anthropic',
      input_per_million: 1.0,
      cache_write_per_million: 1.25,
      cache_read_per_million: 0.1,
      output_per_million: 5.0,
      apply_max_mode_uplift: true,
      source_url: 'https://docs.anthropic.com/en/docs/about-claude/pricing',
      notes: 'Anthropic standard pricing for Claude 4.5 Haiku.',
    },
    'claude-4.5-opus': {
      display_name: 'Claude 4.5 Opus',
      provider: 'anthropic',
      input_per_million: 5.0,
      cache_write_per_million: 6.25,
      cache_read_per_million: 0.5,
      output_per_million: 25.0,
      apply_max_mode_uplift: true,
      source_url: 'https://platform.claude.com/docs/en/about-claude/pricing',
      notes: 'Anthropic standard pricing.',
    },
    'claude-4-sonnet': {
      display_name: 'Claude 4 Sonnet',
      provider: 'anthropic',
      input_per_million: 3.0,
      cache_write_per_million: 3.75,
      cache_read_per_million: 0.3,
      output_per_million: 15.0,
      apply_max_mode_uplift: true,
      source_url: 'https://docs.anthropic.com/en/docs/about-claude/pricing',
      notes: 'Anthropic standard pricing for Claude Sonnet 4.',
    },
    'claude-4.5-sonnet': {
      display_name: 'Claude 4.5 Sonnet',
      provider: 'anthropic',
      input_per_million: 3.0,
      cache_write_per_million: 3.75,
      cache_read_per_million: 0.3,
      output_per_million: 15.0,
      apply_max_mode_uplift: true,
      long_context_input_threshold: 200000,
      long_context_input_multiplier: 2.0,
      long_context_output_multiplier: 1.5,
      long_context_cached_input_multiplier: 2.0,
      source_url: 'https://platform.claude.com/docs/en/about-claude/pricing',
      notes:
        'Anthropic standard pricing with 1M-context premium pricing above 200K total input tokens.',
    },
    'claude-4.6-opus': {
      display_name: 'Claude 4.6 Opus',
      provider: 'anthropic',
      input_per_million: 5.0,
      cache_write_per_million: 6.25,
      cache_read_per_million: 0.5,
      output_per_million: 25.0,
      apply_max_mode_uplift: false,
      source_url: 'https://cursor.com/docs/models/claude-opus-4-6',
      notes:
        'Cursor docs state Opus 4.6 always bills at its base per-token rates, including Max Mode and prompts above 200K context.',
    },
    'claude-4.6-opus-fast': {
      display_name: 'Claude 4.6 Opus (Fast mode)',
      provider: 'anthropic',
      input_per_million: 30.0,
      cache_write_per_million: 37.5,
      cache_read_per_million: 3.0,
      output_per_million: 150.0,
      apply_max_mode_uplift: false,
      source_url: 'https://cursor.com/docs/models/claude-opus-4-6',
      notes:
        'Cursor docs state Opus 4.6 pricing stays at the listed per-token rates in Max Mode; the fast variant uses its own published fast-mode base rates.',
    },
    'claude-4.7-opus': {
      display_name: 'Claude 4.7 Opus',
      provider: 'anthropic',
      input_per_million: 5.0,
      cache_write_per_million: 6.25,
      cache_read_per_million: 0.5,
      output_per_million: 25.0,
      apply_max_mode_uplift: false,
      source_url: 'https://cursor.com/docs/models/claude-opus-4-6',
      notes:
        'Claude Opus 4.7 shares the same per-token rates as Opus 4.6 per Cursor docs.',
    },
    'claude-4.7-opus-fast': {
      display_name: 'Claude 4.7 Opus (Fast mode)',
      provider: 'anthropic',
      input_per_million: 30.0,
      cache_write_per_million: 37.5,
      cache_read_per_million: 3.0,
      output_per_million: 150.0,
      apply_max_mode_uplift: false,
      source_url: 'https://cursor.com/docs/models/claude-opus-4-6',
      notes:
        'Claude Opus 4.7 fast mode shares the same per-token rates as Opus 4.6 fast per Cursor docs.',
    },
    'gemini-3-flash': {
      display_name: 'Gemini 3 Flash',
      provider: 'google',
      input_per_million: 0.5,
      cache_write_per_million: 0.5,
      cache_read_per_million: 0.05,
      output_per_million: 3.0,
      apply_max_mode_uplift: true,
      source_url: 'https://ai.google.dev/gemini-api/docs/pricing',
      notes: 'Google Gemini 3 Flash standard pricing.',
    },
    'gemini-3-pro': {
      display_name: 'Gemini 3 Pro',
      provider: 'google',
      input_per_million: 2.0,
      cache_write_per_million: 2.0,
      cache_read_per_million: 0.2,
      output_per_million: 12.0,
      apply_max_mode_uplift: true,
      source_url: 'https://ai.google.dev/gemini-api/docs/pricing',
      notes: 'Google Gemini 3 Pro standard pricing; same rates as Gemini 3.1 Pro.',
    },
    'gemini-3.1-pro': {
      display_name: 'Gemini 3.1 Pro',
      provider: 'google',
      input_per_million: 2.0,
      cache_write_per_million: 2.0,
      cache_read_per_million: 0.2,
      output_per_million: 12.0,
      apply_max_mode_uplift: true,
      source_url: 'https://cursor.com/docs/models-and-pricing',
      notes: 'Cursor Docs table cites provider API rates.',
    },
    'gemini-3.1-pro-preview': {
      display_name: 'Gemini 3.1 Pro Preview',
      provider: 'google',
      input_per_million: 2.0,
      cache_write_per_million: 2.0,
      cache_read_per_million: 0.2,
      output_per_million: 12.0,
      apply_max_mode_uplift: true,
      source_url: 'https://ai.google.dev/gemini-api/docs/pricing',
      notes: 'Google Gemini API paid tier <= 200k prompt pricing.',
    },
    'gpt-5-mini': {
      display_name: 'GPT-5 Mini',
      provider: 'openai',
      input_per_million: 0.25,
      cache_write_per_million: 0.25,
      cache_read_per_million: 0.025,
      output_per_million: 2.0,
      apply_max_mode_uplift: true,
      source_url: 'https://platform.openai.com/docs/models/gpt-5-mini',
      notes:
        'OpenAI GPT-5 Mini standard pricing; cached input follows the 90% discount pattern.',
    },
    'grok-4-20-thinking': {
      display_name: 'Grok 4.20 (Thinking)',
      provider: 'xai',
      input_per_million: 2.0,
      cache_write_per_million: 2.0,
      cache_read_per_million: 0.5,
      output_per_million: 6.0,
      apply_max_mode_uplift: true,
      source_url: 'https://cursor.com/docs/models/grok-4-20',
      notes:
        'xAI Grok 4.20 reasoning pricing from Cursor Docs; cache-read inferred at 25% of input following xAI Grok 4 series pattern.',
    },
    'gpt-5.1-codex': {
      display_name: 'GPT-5.1 Codex',
      provider: 'openai',
      input_per_million: 1.25,
      cache_write_per_million: 1.25,
      cache_read_per_million: 0.125,
      output_per_million: 10.0,
      apply_max_mode_uplift: true,
      source_url: 'https://developers.openai.com/api/docs/pricing',
      notes: 'OpenAI GPT-5.1 Codex pricing; superseded by GPT-5.2/5.3 Codex.',
    },
    'gpt-5.2-codex': {
      display_name: 'GPT-5.2 Codex',
      provider: 'openai',
      input_per_million: 1.75,
      cache_write_per_million: 1.75,
      cache_read_per_million: 0.175,
      output_per_million: 14.0,
      apply_max_mode_uplift: true,
      source_url: 'https://cursor.com/docs/models-and-pricing',
      notes: 'OpenAI pricing surfaced in Cursor Docs API pool table.',
    },
    'gpt-5.3-codex': {
      display_name: 'GPT-5.3 Codex',
      provider: 'openai',
      input_per_million: 1.75,
      cache_write_per_million: 1.75,
      cache_read_per_million: 0.175,
      output_per_million: 14.0,
      apply_max_mode_uplift: true,
      source_url: 'https://cursor.com/docs/models-and-pricing',
      notes: 'OpenAI pricing surfaced in Cursor Docs API pool table.',
    },
    'gpt-5.3-codex-spark': {
      display_name: 'GPT-5.3 Codex Spark',
      provider: 'openai',
      input_per_million: 1.75,
      cache_write_per_million: 1.75,
      cache_read_per_million: 0.175,
      output_per_million: 14.0,
      apply_max_mode_uplift: true,
      source_url: 'https://developers.openai.com/codex/pricing/',
      notes:
        'GPT-5.3-Codex-Spark is described in OpenAI Codex pricing as a research preview and not available in the API at launch; using GPT-5.3 Codex token rates as the closest available pricing proxy.',
    },
    'gpt-5.4': {
      display_name: 'GPT-5.4',
      provider: 'openai',
      input_per_million: 2.5,
      cache_write_per_million: 2.5,
      cache_read_per_million: 0.25,
      output_per_million: 15.0,
      apply_max_mode_uplift: true,
      long_context_input_threshold: 272000,
      long_context_input_multiplier: 2.0,
      long_context_output_multiplier: 1.5,
      long_context_cached_input_multiplier: 2.0,
      source_url: 'https://developers.openai.com/api/docs/pricing',
      notes:
        'OpenAI standard short-context pricing; above 272K total input tokens, long-context pricing applies for standard, batch, and flex.',
    },
    'gpt-5.4-fast': {
      display_name: 'GPT-5.4 Fast',
      provider: 'openai',
      input_per_million: 5.0,
      cache_write_per_million: 5.0,
      cache_read_per_million: 0.5,
      output_per_million: 30.0,
      apply_max_mode_uplift: true,
      source_url: 'https://cursor.com/docs/models-and-pricing',
      notes:
        "Cursor Docs says GPT-5.4 fast mode is 2x pricing and maps to priority processing; OpenAI's 272K long-context premium note covers standard, batch, and flex rather than priority.",
    },
    'kimi-k2.5': {
      display_name: 'Kimi K2.5',
      provider: 'moonshot',
      input_per_million: 0.6,
      cache_write_per_million: 0.6,
      cache_read_per_million: 0.1,
      output_per_million: 3.0,
      apply_max_mode_uplift: true,
      source_url: 'https://cursor.com/docs/models-and-pricing',
      notes: 'Moonshot pricing surfaced in Cursor Docs API pool table.',
    },
  },
  alias_rules: [
    {
      pattern: '^agent_review$',
      canonical: 'gpt-5.4',
      reason: 'User-directed mapping: agent_review should use GPT-5.4 rates.',
    },
    {
      pattern: '^auto$',
      canonical: 'auto',
      reason: 'Cursor Auto pool.',
    },
    {
      pattern: '^composer-1$',
      canonical: 'composer-1',
      reason: 'Direct Cursor model.',
    },
    {
      pattern: '^composer-1\\.5$',
      canonical: 'composer-1.5',
      reason: 'Direct Cursor model.',
    },
    {
      pattern: '^composer-2$',
      canonical: 'composer-2',
      reason: 'Direct Cursor model.',
    },
    {
      pattern: '^composer-2-fast$',
      canonical: 'composer-2-fast',
      reason: 'Direct Cursor fast variant.',
    },
    {
      pattern: '^claude-4\\.5-haiku(?:-thinking)?$',
      canonical: 'claude-4.5-haiku',
      reason: 'Haiku and thinking variant use same token rates.',
    },
    {
      pattern: '^claude-4\\.5-opus-(?:low|medium|high)(?:-thinking)?$',
      canonical: 'claude-4.5-opus',
      reason: 'All effort/thinking variants use base Opus 4.5 rates.',
    },
    {
      pattern: '^claude-4-sonnet$',
      canonical: 'claude-4-sonnet',
      reason: 'Direct provider model.',
    },
    {
      pattern: '^claude-4\\.5-sonnet(?:-thinking)?$',
      canonical: 'claude-4.5-sonnet',
      reason: 'Sonnet and thinking variant use same token rates.',
    },
    {
      pattern: '^claude-4\\.6-opus-(?:low|medium|high|max)(?:-thinking)?$',
      canonical: 'claude-4.6-opus',
      reason: 'All effort/thinking variants use base Opus 4.6 rates.',
    },
    {
      pattern: '^claude-4\\.6-opus-(?:low|medium|high|max)(?:-thinking)?-fast$',
      canonical: 'claude-4.6-opus-fast',
      reason: 'Fast mode has separate published Cursor pricing.',
    },
    {
      pattern: '^claude-opus-4-7(?:-thinking)?(?:-(?:low|medium|high|max))?$',
      canonical: 'claude-4.7-opus',
      reason: 'All effort/thinking variants use base Opus 4.7 rates.',
    },
    {
      pattern: '^claude-opus-4-7(?:-thinking)?(?:-(?:low|medium|high|max))?-fast$',
      canonical: 'claude-4.7-opus-fast',
      reason: 'Fast mode uses Opus 4.6 fast rates as closest published pricing.',
    },
    {
      pattern: '^gemini-3-flash(?:-preview)?$',
      canonical: 'gemini-3-flash',
      reason: 'Gemini 3 Flash and preview variant use same rates.',
    },
    {
      pattern: '^gemini-3-pro-preview$',
      canonical: 'gemini-3-pro',
      reason: 'Gemini 3 Pro Preview uses same rates as Gemini 3 Pro.',
    },
    {
      pattern: '^gemini-3\\.1-pro$',
      canonical: 'gemini-3.1-pro',
      reason: 'Direct provider model.',
    },
    {
      pattern: '^gemini-3\\.1-pro-preview$',
      canonical: 'gemini-3.1-pro-preview',
      reason: 'Direct provider model.',
    },
    {
      pattern: '^gpt-5-mini$',
      canonical: 'gpt-5-mini',
      reason: 'Direct provider model.',
    },
    {
      pattern: '^grok-4-20-thinking$',
      canonical: 'grok-4-20-thinking',
      reason: 'Direct provider model.',
    },
    {
      pattern: '^gpt-5\\.1-codex(?:-max)?(?:-(?:high|xhigh))?(?:-fast)?$',
      canonical: 'gpt-5.1-codex',
      reason: 'All GPT-5.1 Codex variants use base GPT-5.1 Codex token rates.',
    },
    {
      pattern: '^gpt-5\\.2(?:-codex)?(?:-(?:high|xhigh))?(?:-fast)?$',
      canonical: 'gpt-5.2-codex',
      reason: 'No separate public API SKU found; use base GPT-5.2 Codex token rates.',
    },
    {
      pattern: '^gpt-5\\.3-codex(?:-(?:high|xhigh))?$',
      canonical: 'gpt-5.3-codex',
      reason: 'Reasoning effort variants use base GPT-5.3 Codex token rates.',
    },
    {
      pattern: '^gpt-5\\.3-codex-spark-preview-xhigh$',
      canonical: 'gpt-5.3-codex-spark',
      reason: 'User-directed mapping to GPT-5.3 Codex Spark.',
    },
    {
      pattern: '^gpt-5\\.3-codex(?:-(?:high|xhigh))?-fast$',
      canonical: 'gpt-5.3-codex',
      reason:
        'No separate public API price found for Codex fast variants; use base GPT-5.3 Codex token rates.',
    },
    {
      pattern: '^gpt-5\\.4-(?:high|medium|xhigh)$',
      canonical: 'gpt-5.4',
      reason: 'Reasoning effort variants use base GPT-5.4 token rates.',
    },
    {
      pattern: '^gpt-5\\.4-(?:high|medium|xhigh)-fast$',
      canonical: 'gpt-5.4-fast',
      reason: 'Cursor Docs publishes GPT-5.4 fast pricing at 2x base.',
    },
    {
      pattern: '^kimi-k2\\.5$',
      canonical: 'kimi-k2.5',
      reason: 'Direct provider model.',
    },
    {
      pattern: '^kimi-k2p5$',
      canonical: 'kimi-k2.5',
      reason: 'Cursor export alias for Kimi K2.5.',
    },
    {
      pattern: '^[Pp]remium \\((?:[Gg][Pp][Tt]-5\\.3-[Cc]odex|[Cc]odex 5\\.3)\\)$',
      canonical: 'gpt-5.3-codex',
      reason: 'Premium route still bills at selected model API rate.',
    },
  ],
};
